name: Ontology Documentation CI
# copy from https://github.com/opengeospatial/ogc-geosparql/blob/master/.github/workflows/pylode.yml
on: 
  push: 
      branches:
          - master
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation ðŸ”§
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         # sudo apt-get install gcc libpq-dev -y
         # sudo apt-get install python-dev -y
         # sudo apt-get install asciidoctor ruby -y
         # sudo gem install --pre asciidoctor-pdf
         sudo apt-get install python3-dev python3-venv -y
         sudo pip3 install pylode
         mkdir testdocs

         # cp index.html docs/index.html
         cd Loop3D-GSO
         pylode  -i Examples/GSO-ExampleComplexContacts.ttl   -o  ../testdocs/ex-complexcontact.html -f html
         
         # cp ../../1.0/geo.ttl ../../1.0/profile.ttl ../../1.0/funcsrules.ttl ../../1.0/sf_geometries.ttl ../../1.0/11-052r4_OGC_GeoSPARQL.pdf .
         # pylode -i ../../1.0/geo.ttl -o index.html
         # pylode -i ../../1.0/profile.ttl -o profile.html -p prof
         # pylode -i ../../1.0/funcsrules.ttl -o funcsrules.html -p vocpub
         # pylode -i ../../1.0/sf_geometries.ttl -o sf_geometries.html -p vocpub
         #pylode -u http://schemas.opengis.net/gml/3.2.1/gml_32_geometries.rdf -o gml_geometries.html -p vocpub
         # cd ../geosparql11/
         # asciidoctor ../../1.1/spec/00-GeoSPARQL.adoc -o spec.html
         
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: testdocs/
